import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(160C353C-ED83-4dd3-B39F-A0C73E54B8A1),
	dual,
	helpstring("aaa"),
	pointer_default(unique)
]
interface IBdLogView : IDispatch
{
	[id(1), helpstring("bbb")]
	HRESULT MessageBox([in] BSTR text, [in,optional] VARIANT title);

	[id(2), helpstring("logcenter")]
	HRESULT GetLogCenter([out,retval] IDispatch** ppObj);
};

[
	object,
	uuid(E6A15F6D-DE26-4D4D-984A-7B983D8FBA5E),
	dual,
	helpstring("Get Log Item"),
	pointer_default(unique)
]
interface ILogItem : IDispatch
{
	[propget]
	HRESULT time([out,retval] double* pTime);

	[propget]
	HRESULT level([out,retval] UINT* pClass);

	[propget]
	HRESULT tag([out,retval] BSTR* pTag);

	[propget]
	HRESULT pid([out,retval] UINT* pPID);

	[propget]
	HRESULT tid([out,retval] UINT* pTID);

	[propget]
	HRESULT depth([out,retval] UINT* pDepth);
	
	[propget]
	HRESULT content([out,retval] BSTR* pContent);
};

[
	object,
	uuid(718BD1AA-4B70-45D1-8D49-B9018DDFA18C),
	dual,
	helpstring("LogCenter"),
	pointer_default(unique)
]
interface ILogCenter : IDispatch
{
	[id(1), helpstring("Get Log Count")]
	HRESULT GetLogCount([out, retval] long* pCount);

	[id(2), helpstring("logitem")]
	HRESULT GetLogItem([in] long index, [out,retval] IDispatch** ppObj);
};


[
	uuid(565E617D-43FF-41cc-8EC3-D41A38A887D4),
	version(1.0),
	helpstring("BDLogView")
]
library BdLogviewLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(F5C68AE4-272E-4271-BF37-C7D122484089), 
		helpstring("ccc")
	]
	coclass BdLogView
	{
		[default] interface IBdLogView;
	};

	[ 
		uuid(6350AE64-BFE8-4640-8D23-4310EB21A63C),
		helpstring("LogItem")
	]
	coclass LogItem
	{
		[default] interface ILogItem;
	};

	[
		uuid(85A42930-3187-48C9-A152-16C3515104BD),
		helpstring("LogCenter")
	]
	coclass LogCenter
	{
		[default] interface ILogCenter;
	};
};
